documentation:
  - changed-files:
      - any-glob-to-any-file: "docs/*"

source:
  - all:
      - changed-files:
          - any-glob-to-any-file: "Uqs/**/*"
          - all-globs-to-all-files:
              - "!Uqs/docs/**/*"
              - "!Uqs/logs/**/*"
