documentation:
  - changed-files:
      - any-glob-to-any-file: "docs/*"

source:
  - changed-files:
      - any-glob-to-any-file: "**"
      - all-globs-to-all-files:
          - "!docs/*"
          - "!.github/*"
